title:        'sjue.net'
tagline:      'living your legacy'
description:  'think-love-act'
url:          http://sjue.net
version:      .003
author:
  name:       'Brad Sjue'
  email:      ''
markdown: kramdown
twitter_username: bradsjue